/* Generated automatically by the program `genattr-common'
   from the machine description file `md'.  */

#ifndef GCC_INSN_ATTR_COMMON_H
#define GCC_INSN_ATTR_COMMON_H

enum attr_type {TYPE_ABS, TYPE_ADC, TYPE_ADCL, TYPE_ADD, TYPE_ADDHL, TYPE_ADDL, TYPE_AND, TYPE_ANDL, TYPE_ASL, TYPE_ASLL, TYPE_ASR, TYPE_ASRL, TYPE_ATLDLOP, TYPE_ATLDOP, TYPE_BBIT, TYPE_BCLR, TYPE_BI, TYPE_BIC, TYPE_BL, TYPE_BLOCK, TYPE_BMSK, TYPE_BRANCH, TYPE_BRANCHCC, TYPE_BRCC, TYPE_BRK, TYPE_BSET, TYPE_BSETL, TYPE_BTST, TYPE_BXOR, TYPE_BXORL, TYPE_CMP, TYPE_DBNZ, TYPE_DIV, TYPE_DIVL, TYPE_DMB, TYPE_DMPYWH, TYPE_EX, TYPE_EXT, TYPE_FADD, TYPE_FCMP, TYPE_FD2S, TYPE_FDIV, TYPE_FFS, TYPE_FH2S, TYPE_FLAG, TYPE_FLS, TYPE_FMADD, TYPE_FMAX, TYPE_FMIN, TYPE_FMOV, TYPE_FMSUB, TYPE_FMUL, TYPE_FNMADD, TYPE_FNMSUB, TYPE_FP2INT, TYPE_FP2UINT, TYPE_FRND, TYPE_FS2D, TYPE_FS2H, TYPE_FSGNJ, TYPE_FSGNJN, TYPE_FSGNJX, TYPE_FSQRT, TYPE_FSUB, TYPE_INT2FP, TYPE_JL, TYPE_JUMP, TYPE_LD, TYPE_LLOCK, TYPE_LR, TYPE_LSR, TYPE_LSRL, TYPE_MAC, TYPE_MAX, TYPE_MAXL, TYPE_MIN, TYPE_MINL, TYPE_MOD, TYPE_MODL, TYPE_MOVE, TYPE_MOVECC, TYPE_MPY, TYPE_MPYL, TYPE_NEG, TYPE_NOP, TYPE_NORM, TYPE_NORMH, TYPE_NORML, TYPE_NOT, TYPE_NOTL, TYPE_OR, TYPE_ORL, TYPE_QMACH, TYPE_QMPYH, TYPE_RETURN, TYPE_ROL, TYPE_ROR, TYPE_RTIE, TYPE_SBC, TYPE_SBCL, TYPE_SCOND, TYPE_SETCC, TYPE_SEX, TYPE_SR, TYPE_ST, TYPE_SUB, TYPE_SUBL, TYPE_SWAP, TYPE_SWAPE, TYPE_SWAPEL, TYPE_SWAPL, TYPE_SYNC, TYPE_TRAP, TYPE_TST, TYPE_UDIV, TYPE_UDIVL, TYPE_UINT2FP, TYPE_UMOD, TYPE_UMODL, TYPE_UNKNOWN, TYPE_VADD, TYPE_VADDSUB, TYPE_VFADD, TYPE_VFADDSUB, TYPE_VFBFLYL, TYPE_VFBFLYM, TYPE_VFDIV, TYPE_VFEXCH, TYPE_VFEXT, TYPE_VFINS, TYPE_VFMUL, TYPE_VFPACKL, TYPE_VFPACKM, TYPE_VFREP, TYPE_VFSUB, TYPE_VFSUBADD, TYPE_VFUNPKL, TYPE_VFUNPKM, TYPE_VMAC2H, TYPE_VMPY2H, TYPE_VPACK, TYPE_VSUB, TYPE_VSUBADD, TYPE_XBFU, TYPE_XOR, TYPE_XORL};
enum attr_iscompact {ISCOMPACT_YES, ISCOMPACT_NO, ISCOMPACT_MAYBE};
enum attr_predicable {PREDICABLE_YES, PREDICABLE_NO};
enum attr_cpu_facility {CPU_FACILITY_STD, CPU_FACILITY_CD, CPU_FACILITY_NCD};
enum attr_enabled {ENABLED_NO, ENABLED_YES};
enum attr_slottable {SLOTTABLE_FALSE, SLOTTABLE_TRUE};
enum attr_call_slottable {CALL_SLOTTABLE_FALSE, CALL_SLOTTABLE_TRUE};
enum attr_delay_slot_filled {DELAY_SLOT_FILLED_NO, DELAY_SLOT_FILLED_YES};
#define INSN_SCHEDULING
#define DELAY_SLOTS 1

#endif /* GCC_INSN_ATTR_COMMON_H */
